# Generated by Django 4.0.4 on 2022-05-27 06:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_description', ckeditor.fields.RichTextField()),
                ('document_source', models.CharField(max_length=200)),
                ('type_document', models.CharField(max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
