# Generated by Django 4.0.4 on 2022-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
